refactor: vpn and dns-changer scripts

diff --git a/utils/.scripts/dns-changer b/utils/.scripts/dns-changer
--- a/utils/.scripts/dns-changer
+++ b/utils/.scripts/dns-changer
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-declare -A dns_servers=(
+declare -A DNS_SERVERS=(
     ["Electro"]="78.157.42.100,78.157.42.101"
     ["403"]="10.202.10.202,10.202.10.102"
     ["Shecan"]="178.22.122.100,185.51.200.2"
@@ -11,45 +11,47 @@ declare -A dns_servers=(
 
 display_dns_list() {
     echo "Available DNS Servers:"
-    i=1
-    for dns_name in "${!dns_servers[@]}"; do
-        echo "$i. ${dns_name}"
+    local i=1
+    for dns_name in "${!DNS_SERVERS[@]}"; do
+        echo "$i. $dns_name: (${DNS_SERVERS[$dns_name]})"
         ((i++))
     done
 }
 
 select_dns() {
-    read -p "Select a DNS server (enter the name or number): " selected_input
+    local input
+    read -p "Select a DNS server (enter the name or number): " input
 
-    if [[ $selected_input =~ ^[0-9]+$ ]]; then
-        if ((selected_input >= 1 && selected_input <= ${#dns_servers[@]})); then
-            selected_name=$(echo "${!dns_servers[@]}" | cut -d ' ' -f $selected_input)
-            selected_dns=${dns_servers[$selected_name]}
-            echo "Selected DNS server: $selected_dns"
-        else
-            echo "Invalid number. Please select a valid number."
-            select_dns
-        fi
+    if [[ $input =~ ^[0-9]+$ ]]; then
+        local dns_index=1
+        for dns_name in "${!DNS_SERVERS[@]}"; do
+            if ((dns_index == input)); then
+                echo "$dns_name"
+                return
+            fi
+            ((dns_index++))
+        done
     else
-        if [[ -n ${dns_servers[$selected_input]} ]]; then
-            selected_dns=${dns_servers[$selected_input]}
-            echo "Selected DNS server: $selected_dns"
-        else
-            echo "Invalid name. Please select a valid name."
-            select_dns
+        if [[ -n ${DNS_SERVERS[$input]} ]]; then
+            echo "$input"
+            return
         fi
     fi
+
+    echo "Invalid selection. Please try again." >&2
+    select_dns
 }
 
 update_resolv_conf() {
-    sudo sh -c "echo '' > /etc/resolv.conf"
-    IFS=',' read -ra dns_array <<<"$1"
+    local selected_dns="$1"
+    sudo bash -c "echo '' > /etc/resolv.conf"
+    IFS=',' read -ra dns_array <<<"$selected_dns"
     for dns in "${dns_array[@]}"; do
         echo "nameserver $dns" | sudo tee -a /etc/resolv.conf >/dev/null
     done
-    echo "Updated /etc/resolv.conf with DNS servers: $1"
+    echo "Updated /etc/resolv.conf with DNS servers: $selected_dns"
 }
 
 display_dns_list
-select_dns
-update_resolv_conf "$selected_dns"
+selected_name=$(select_dns)
+update_resolv_conf "${DNS_SERVERS[$selected_name]}"
diff --git a/utils/.scripts/vpn b/utils/.scripts/vpn
--- a/utils/.scripts/vpn
+++ b/utils/.scripts/vpn
@@ -1,26 +1,63 @@
 #!/bin/bash
 
-# SERVER="nl25.apibaz.info"
-# SERVER="iosmtn.apibaz.info"
-# SERVER="mci1.apibaz.info"
-# SERVER="newnl.apibaz.info"
-# SERVER="en1.apibaz.info"
-# SERVER="en2.apibaz.info"
-# SERVER="mcis8.apibaz.info"
-# SERVER="mciwin.apibaz.info"
-# SERVER="mciwin.apibaz.info"
-SERVER="vps-2dbe0949.vps.ovh.net"
-SERVER="vps-1b59076c.vps.ovh.net"
 USER="vbaz568161"
 PASSWORD="2489"
 
-main() {
-    echo "Connecting to VPN at $SERVER as $USER..."
+declare -A VPN_SERVERS=(
+    ["iOS MTN"]="iosmtn.apibaz.info"
+    ["MCI 1"]="mci1.apibaz.info"
+    ["NewNl"]="newnl.apibaz.info"
+    ["EN 1"]="en1.apibaz.info"
+    ["EN 2"]="en2.apibaz.info"
+    ["MCIS 8"]="mcis8.apibaz.info"
+    ["MCI Windows"]="mciwin.apibaz.info"
+    ["OVH 1"]="vps-2dbe0949.vps.ovh.net"
+    ["OVH 2"]="vps-1b59076c.vps.ovh.net"
+)
 
-    sudo openconnect --server="$SERVER" --user="$USER" --no-dtls <<END
+display_vpn_list() {
+    echo "Available VPN Servers:"
+    local i=1
+    for vpn_name in "${!VPN_SERVERS[@]}"; do
+        echo -e "$i. $vpn_name: (${VPN_SERVERS[$vpn_name]})"
+        ((i++))
+    done
+}
+
+select_vpn_server() {
+    local input
+    read -p "Select a VPN server (enter the name or number): " input
+
+    if [[ $input =~ ^[0-9]+$ ]]; then
+        local vpn_index=1
+        for vpn_name in "${!VPN_SERVERS[@]}"; do
+            if ((vpn_index == input)); then
+                echo "$vpn_name"
+                return
+            fi
+            ((vpn_index++))
+        done
+    else
+        if [[ -n ${VPN_SERVERS[$input]} ]]; then
+            echo "$input"
+            return
+        fi
+    fi
+
+    echo "Invalid selection. Please try again." >&2
+    select_vpn_server
+}
+
+connect_vpn() {
+    local server="$1"
+    echo "Connecting to VPN at $server as $USER..."
+
+    sudo openconnect --server="$server" --user="$USER" --no-dtls <<END
 yes
 $PASSWORD
 END
 }
 
-main
+display_vpn_list
+selected_name=$(select_vpn_server)
+connect_vpn "${VPN_SERVERS[$selected_name]}"
